# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayquaters',
            name='elements',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='displayquaters',
            name='engraver',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='displayquaters',
            name='release_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='displayquaters',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
