# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins_web_app', '0002_auto_20170413_0843'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisplayQuaters',
            new_name='DisplayQuarters',
        ),
        migrations.RenameField(
            model_name='displayquarters',
            old_name='link',
            new_name='image_link',
        ),
    ]
